# Generated by Django 6.1.1 on 2026-10-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.PositiveIntegerField(help_text='OPIS Truckstop ID', unique=True)),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.PositiveIntegerField()),
                ('retail_price', models.DecimalField(decimal_places=6, help_text='USD per gallon', max_digits=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geocode_precision', models.CharField(blank=True, choices=[('exit', 'Interstate exit'), ('city', 'City centroid')], max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['opis_id'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='stations_fu_latitud_a20c3d_idx')],
            },
        ),
    ]
